FROM maven:3.6-jdk-8
ARG PSLIBVERSION

RUN mkdir -p /data/ebx/lib
WORKDIR /data/ebx

COPY presales-toolbox.jar /data/ebx/lib
COPY adminpermissionsutil-1.0.jar /data/ebx/lib

ENV groupIdPsLibs=com.tibco.ebx.ps
ENV repoId=psus.ebx.repo.releases
ENV repoUrl=http://ec2-54-85-42-45.compute-1.amazonaws.com:8081/repository/maven-releases

ENV libFolder=/data/ebx/lib
ENV pslibVersion=${PSLIBVERSION}

COPY pushPsLibs.sh .
RUN chmod +x pushPsLibs.sh
COPY settings.xml .

CMD ["/data/ebx/pushPsLibs.sh"]
